config/routes.rb
Rails.application.routes.draw do
  root "pages#app"
  resources :orders
  resources :drinks

  get '/app' => 'pages#app'

  get '/pubs/search/:query' => 'pubs#search'
  get '/pub/:id' => 'pubs#show'
  get 'pubs/geosearch/:distance' => 'pubs#geo_search'
  resources :pubs

  resources :users, except: [:index]
  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

end

app/models/pub.rb
class Pub < ApplicationRecord
  has_many :drinks
  has_many :orders, through: 'drinks'
  geocoded_by :location
  after_validation :geocode

  def address
    location
  end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_pub, only: [:show, :edit, :update, :destroy]

  # GET /pubs
  # GET /pubs.json
  def index
    @pubs = Pub.all

  end

  # GET /pubs/1
  # GET /pubs/1.json
  def show
    @pub = Pub.find(params[:id])
    render json: @pub, include: 'drinks'
  end

  # ILIKE query is used here so it will find any matching partial queries lower or upper and will feed me the JSON response back 
  def search
    render json: Pub.where('name || location ILIKE ?', "%#{params[:query]}%")
  end

  def geo_search
    render json: Pub.near("#{params[:coords]}", '15, units: :km')
  end

  # GET /pubs/new
  def new
    @pub = Pub.new
  end

  # GET /pubs/1/edit
  def edit
  end

  # POST /pubs
  # POST /pubs.json
  def create
    @pub = Pub.new(pub_params)

    respond_to do |format|
      if @pub.save
        format.html { redirect_to @pub, notice: 'Pub was successfully created.' }
        format.json { render :show, status: :created, location: @pub }
      else
        format.html { render :new }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pubs/1
  # PATCH/PUT /pubs/1.json
  def update
    respond_to do |format|
      if @pub.update(pub_params)
        format.html { redirect_to @pub, notice: 'Pub was successfully updated.' }
        format.json { render :show, status: :ok, location: @pub }
      else
        format.html { render :edit }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pubs/1
  # DELETE /pubs/1.json
  def destroy
    @pub.destroy
    respond_to do |format|
      format.html { redirect_to pubs_url, notice: 'Pub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pub
      @pub = Pub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pub_params
      params.require(:pub).permit(:name, :location)
    end
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/views/pubs/_form.html.erb
<%= form_with(model: pub, local: true) do |form| %>
  <% if pub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pub.errors.count, "error") %> prohibited this pub from being saved:</h2>

      <ul>
      <% pub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pubs/edit.html.erb
<h1>Editing Pub</h1>

<%= render 'form', pub: @pub %>

<%= link_to 'Show', @pub %> |
<%= link_to 'Back', pubs_path %>

app/views/pubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pubs.each do |pub| %>
      <tr>
        <td><%= pub.name %></td>
        <td><%= pub.location %></td>
        <td><%= link_to 'Show', pub %></td>
        <td><%= link_to 'Edit', edit_pub_path(pub) %></td>
        <td><%= link_to 'Destroy', pub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pub', new_pub_path %>

app/views/pubs/new.html.erb
<h1>New Pub</h1>

<%= render 'form', pub: @pub %>

<%= link_to 'Back', pubs_path %>

app/views/pubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pub.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pub.location %>
</p>

<%= link_to 'Edit', edit_pub_path(@pub) %> |
<%= link_to 'Back', pubs_path %>